In [1]:
isim = input("Isminizi Girin= ")

Isminizi Girin= Mehmet Şahin Çetin


In [2]:
print("Hosgeldin {}, öncelikle burada olduğun için çok mutluyuz, seni bu test ile karşılaştırdığımız için biz de üzgünüz fakat adil bir seçim yapmamız gerekiyor.".format(isim))

Hosgeldin Mehmet Şahin Çetin, öncelikle burada olduğun için çok mutluyuz, seni bu test ile karşılaştırdığımız için biz de üzgünüz fakat adil bir seçim yapmamız gerekiyor.


## Python

In [3]:
#İleri kullanacağımız fonksiyonlar için bu hücreyi çalıştırın

import numpy as np
import math

### Soru 0:

Python Versiyonunuzu Yazdırın.

In [4]:
#Kodun buraya gelecek
import platform
platform.python_version()

'3.7.1'

### Soru 1:

Telefon numaranızın son hanesindeki rakamdan başlayarak, son iki hanesindeki sayıya kadar devam eden bir liste oluşturun, bu listedeki sayıların ortalamasını ve toplamını yazdırın. (son iki hane sayısı 10'dan küçük olanlar için verilecek değer 70'dir.)

In [5]:
no = int(input("Telefon Numarınızı Girin= "))

Telefon Numarınızı Girin= 5443850706


### Cevap 1:

In [6]:
str_no = str(no)
#İçerisine telefon no rakamları eklenmek üzere boş liste tanımlanır.
list = []
for i in str_no:
    list.append(int(i))
print(list)
#listenin son iki hanesi alınarak son_iki_hane isimli değişkene eşitlenir
son_iki_hane= str(list[-2])+str(list[-1])
print(son_iki_hane)
son_iki_hane_int = int(son_iki_hane)
#son iki haneyi kontrol etmek üzere if-else yapısı kurulur.
asil_liste = []
if son_iki_hane_int<10:
    #listenin son iki hanesi 10dan küçük olduğu için onun yerine 70 kullanılır.
    for i in range(70):
        asil_liste.append(i)     
else:
    for i in range(son_iki_hane_int):
        asil_liste.append(i)
del asil_liste[0:list[-1]]         
#listenin son hali için liste bastırılır    
print(asil_liste)
#listedeki sayıları toplamak için toplam değeri tanımlanır.
toplam = 0
for i in asil_liste:
    toplam +=i                   
print("Ortalama : " + str(toplam/len(asil_liste)))
print("Toplam : " + str(toplam))

[5, 4, 4, 3, 8, 5, 0, 7, 0, 6]
06
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69]
Ortalama : 37.5
Toplam : 2400


### Soru 2:

Alt satırdaki yazi degiskeni olan hücreyi çalıştırın ve for döngüsüyle bu yazının her harfini bir listeye eleman olarak aktarın.

Not: Boşluklar ve noktalama işaretlerini listeye almamalısınız.

In [7]:
yazi = "uludag deeplearning teknik bir topluluktur."

### Cevap 2:

In [8]:
list_yazi = []
for i in yazi:
    if i == (" ") or i == "." or i == ",":
        pass
    else:
        list_yazi.append(i)
print(list_yazi)    

['u', 'l', 'u', 'd', 'a', 'g', 'd', 'e', 'e', 'p', 'l', 'e', 'a', 'r', 'n', 'i', 'n', 'g', 't', 'e', 'k', 'n', 'i', 'k', 'b', 'i', 'r', 't', 'o', 'p', 'l', 'u', 'l', 'u', 'k', 't', 'u', 'r']


### Soru 3:

Sigmoid fonksiyonunu, sigmoid adını verdiğiniz fonksiyonla tanımlayınız.

![sigmoid](sigmoid.jpg)

In [12]:
# Örnek: 
def fonk_ornek(girdi):
    pass #Burası koduna dahil olmayacak.
    sonuc = islem1*islem2/girdi
    return sonuc

### Cevap 3:

In [9]:
def sigmoid(x):
    sonuc = 1/(1+math.e**-x)
    return sonuc
sigmoid(1) #1 değeri için sigmoid fonksiyonu değeri

0.7310585786300049

## Numpy

### Soru 1:

5x5 boyutunda, sıfırlar, birler matrislerini oluşturun.

### Cevap 1:

In [10]:
bese_bes_sifirlar_matrisi = np.zeros((5,5))
print(bese_bes_sifirlar_matrisi)
bese_bes_birler_matrisi = np.ones((5,5))
print(bese_bes_birler_matrisi)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Soru 2:

İki farklı 5x5 random sayılardan oluşan iki matris oluşturun. Bu matrisleri matris çarpımı yöntemiyle çarpın

In [11]:
random_matrix_1 = np.random.randint(0,10,(5,5))
random_matrix_2 = np.random.randint(0,10,(5,5))
print("1.Matris")
print(random_matrix_1)
print("2.Matris")
print(random_matrix_2)
print("Matrislerin Toplamı")
print(random_matrix_1 + random_matrix_2)

1.Matris
[[4 6 2 1 1]
 [3 1 8 5 1]
 [4 1 7 8 0]
 [2 6 5 7 4]
 [3 9 5 8 7]]
2.Matris
[[8 7 3 9 4]
 [6 3 3 6 5]
 [8 2 5 8 1]
 [0 5 8 8 8]
 [3 0 5 6 6]]
Matrislerin Toplamı
[[12 13  5 10  5]
 [ 9  4 11 11  6]
 [12  3 12 16  1]
 [ 2 11 13 15 12]
 [ 6  9 10 14 13]]


### Soru 3:

100 Uzunluklu bir liste oluşturun, önce tek ve çift sayıları döngülerle tek ve çift adlı iki listeye ayırın, bu iki listeyi 5x10 boyutunda iki matris haline getirin.

### Cevap 3:

In [12]:
yuzluk_liste = []
for i in range(100): 
    yuzluk_liste.append(i)
print(yuzluk_liste)
tek_listesi = []
cift_listesi = []
for i in yuzluk_liste:
    if i % 2 == 0:
        tek_listesi.append(i)
    else:
        cift_listesi.append(i)
np_tek_listesi = np.array(tek_listesi)
np_cift_listesi = np.array(cift_listesi)
print("Tek Listesi")
print(np_tek_listesi)
print("Çift Listesi")
print(np_cift_listesi)
print("5x10 Boyutlarındaki Tek Listesi")
print(np_tek_listesi.reshape(5,10))
print("5x10 Boyutlarındaki Çift Listesi")
print(np_cift_listesi.reshape(5,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
Tek Listesi
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
Çift Listesi
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
5x10 Boyutlarındaki Tek Listesi
[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]
5x10 Boyutlarındaki Çift Listesi
[[ 1  3  5  7  9 11 13 15 17 19]
 [21 23 25 2

### Soru 0: (Opsiyonel)

Buradaki matematiksel ifadeleri python ile yazmanızı bekliyoruz. Aşağıda yazılan fonksiyonların her biri size ekstra bazı puanlar kazandıracaktır.

![1.](1.jpg "1")

In [13]:
def fonksiyon1(boyut):
    list = np.random.rand(boyut)
    print(list)
    np_list = np.array(list)
    toplam = 0.0
    for i in list:
        toplam +=(np.mean(np_list)-i) ** 2
    return (1/(np_list.size))*toplam
fonksiyon1(15)    

[0.25211882 0.83690276 0.37079015 0.890135   0.19696221 0.85967343
 0.09221496 0.29171356 0.624032   0.42246503 0.99560097 0.88867423
 0.44460081 0.12001202 0.07204753]


0.10147062146986519

![3.](3.jpg "3")

In [14]:
def fonksiyon2(boyut):
    list = np.random.rand(boyut)
    print(list)
    np_list = np.array(list)
    toplam = 0.0
    for i in list:
        toplam += i * math.log10(np.mean(np_list)) + (1-i) * math.log10(1-np.mean(np_list))
    return (-1/(np_list.size)) * toplam
fonksiyon2(30) 

[0.15299741 0.3481242  0.00404708 0.26558911 0.08976304 0.73953519
 0.74280974 0.81993706 0.21560078 0.83770618 0.87513623 0.6695304
 0.47861195 0.45313206 0.86407708 0.71687119 0.03363777 0.41626295
 0.4482083  0.64308886 0.91773636 0.54096714 0.22281873 0.36228548
 0.90035948 0.76721153 0.14454757 0.62373825 0.13434566 0.73121366]


0.30100532248791284

![2.](2.jpg "2")

In [15]:
def fonksiyon3(boyut1,boyut2,boyut3):
    list1 = np.random.rand(boyut1)
    list2 = np.random.rand(boyut2)
    list3 = np.random.rand(boyut3)
    print(list1)
    print(list2)
    print(list3)
    np_list1 = np.array(list1)
    np_list2 = np.array(list2)
    np_list3 = np.array(list3)
    list_uzun = []
    list_uzun.append(list1)
    list_uzun.append(list2)
    list_uzun.append(list3)
    np_list_uzun = np.array(list_uzun)
    print(list_uzun)
    toplam = 0.0
    for i in np_list_uzun:
        for j in i:
            toplam += j * math.log10(np.mean(i)) + (1-j) * math.log10(1-np.mean(i))
    return (-1/(np_list_uzun.size)) * toplam
fonksiyon3(5,5,5) 

[0.53786992 0.89314775 0.13211496 0.22168007 0.43523211]
[0.01392487 0.95970392 0.9438304  0.71202995 0.09243801]
[0.90048963 0.92605581 0.24208877 0.33512642 0.76783352]
[array([0.53786992, 0.89314775, 0.13211496, 0.22168007, 0.43523211]), array([0.01392487, 0.95970392, 0.9438304 , 0.71202995, 0.09243801]), array([0.90048963, 0.92605581, 0.24208877, 0.33512642, 0.76783352])]


0.29426099289358104